### ISSUE TITLE
The calendar header is formatted incorrectly.

### ISSUE THREAD

**Issue by raj-pel** [Azurewarth0920/vue-daterange-picker#2]
<img width="697" alt="Screenshot 2024-04-29 at 12 38 22 AM" src="https://github.com/Azurewarth0920/vue3-range-calendar/assets/3490658/b0fe3420-020f-4db9-8f9d-c2ce39ead792">
<img width="261" alt="Screenshot 2024-04-29 at 12 38 03 AM" src="https://github.com/Azurewarth0920/vue3-range-calendar/assets/3490658/9d55f12f-849a-4082-a39d-1ae6fa31d4fc">

On Laptop shows 29 Monday and In Calender Shows 29 Sunday, Please have a look once

**Comment by Azurewarth0920** [comment]
Thanks for reporting.

Fixed in #3, v0.3.2
